name: Build

on:
  pull_request:
  push:
    branches:
      - master
  schedule:
    # Prime the caches every Monday
    - cron: 0 1 * * MON

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        ocaml-compiler:
          - "5.3"
          - "5.4"
        include:
          - os: macos-latest
            ocaml-compiler: "5.4"

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout tree
        uses: actions/checkout@v6

      - name: Set-up OCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}
          opam-pin: false

      - name: Re-install OpenSSL on macOS
        if: runner.os == 'macOS'
        run: brew update && brew reinstall openssl@3

      - name: Install external dependencies
        # The version of binaryen available in ubuntu is too old and doesn't
        # contain wasm-merge needed by wasm_of_ocaml.
        if: runner.os == 'Linux'
        run: |
          curl -sL https://github.com/WebAssembly/binaryen/releases/download/version_129/binaryen-version_129-x86_64-linux.tar.gz | sudo tar xz -C /usr/local --strip-components=1

      - run: opam pin add -n eliom https://github.com/ocsigen/eliom.git

      - run: opam install . --deps-only

      - run: opam exec -- dune build @install
